# Generated by Django 3.0 on 2020-10-24 13:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Carspace',
            new_name='CarspaceModel',
        ),
    ]
