# Generated by Django 3.0 on 2020-11-02 11:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0004_carplan_tyremodel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carplan',
            name='car',
        ),
        migrations.RemoveField(
            model_name='tyremodel',
            name='car',
        ),
        migrations.AddField(
            model_name='carspacemodel',
            name='plan',
            field=models.ForeignKey(default=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app1.Carplan'),
        ),
        migrations.AddField(
            model_name='carspacemodel',
            name='tyres',
            field=models.ForeignKey(default=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app1.TyreModel'),
        ),
    ]
