# Generated by Django 3.0 on 2020-11-03 10:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0007_auto_20201102_1936'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carspacemodel',
            name='plan',
        ),
        migrations.RemoveField(
            model_name='carspacemodel',
            name='tyres',
        ),
        migrations.AddField(
            model_name='carspacemodel',
            name='car_plan',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='app1.Carplan'),
        ),
        migrations.AddField(
            model_name='carspacemodel',
            name='car_tyres',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='app1.TyreModel'),
        ),
    ]
